title: Exploit Semi-public Facing Application
description: 
severity: High
tags:
  - oran
  - 5gcore
  - generic
detectionMethods: # Mechanisms to detect the threat
   - name: networkTraffic
     tag: [mitre, ds0029]
     description: desc
     url: https://fight.mitre.org/data%20sources/DS0029
mitigationMethods: # Mechanisms to mitigate the threat
securityActions:
  - mitre/networkTraffic
securityIntentBinding: # Set of labels, annotations describing workloads who would be impacted by this threat
preDeploymentConsiderations: [ ] # Anything that can be done in CI/CD pipelines that can alleviate this threat
references:
  - name: FGT5029
    url: https://fight.mitre.org/techniques/FGT5029
